swetha-200217/DSA-Training

palindrome_string.py

To check whether the string is palindrome or not

DT-16 palindrome string check

---

missing_num_arr.py

To identify the missing number in an array

DT-19 missing number identification in array

---

missing_num_arr.py
word_break.py

word break problem to check whether the input string can segmented

Dt 33 word break problem

---

LinkedList.java

Linked List Problem to find the middle node of it

DT-28-Find-the-middle-of-a-linked-list

---

PalindromeLinkedList.java

linked list problem to check if it is a palindrome or not

DT-29-Check-if-a-linked-list-is-palindromic

---

first_nonrep_char.py

To find the first non repeating character in a string

DT-18 find first nonrepeated char

---

Duplicate.java

Find Duplicate

---

AnagramChecker.java
RevLinkedList.java

Dt 7 valid anagram

---

RevLinkedList.java

Reverse LinkedList

---

Reversing a linked list.py

Reversing a linked list

---

best time to buy and sell stock.py

Best Time to Buy and Sell Stock

 DT-11-best-time-to-buy-and-sell-stock

---

.vscode/settings.json
PalindromeDescendant.java
PostfixEvaluation.java
SortContacts.java

write a program that sorts a list of contacts based on their last names. Each contact is represented as a string in the format
"FirstName LastName".

Dt 22 sorting contact list based on last names

---

PalindromeDescendant.java

A number may not be a palindrome, but its descebant can be . A number's direct child is created by summing each pair of adjacent
digits to create the digits of the next number.

Palindrome descendant

---

.vscode/settings.json
PalindromeDescendant.java
PostfixEvaluation.java

Postfix notation is a mathematical notation where operators follow their operands.

Dt 24 postfix notation evaluation

---

.vscode/settings.json
Knapsack.java
PalindromeDescendant.java
PostfixEvaluation.java
SortContacts.java

The Knapsack Problem involves selecting items with given weights and values to maximize total value without exceeding a weight limit. This repository provides algorithms to solve this optimization challenge.

Dt 25 knapsack problem

---

ClimbStairs.java
InvertBinaryTree.java

Dt 9 claimbing stairs

---

coin change problem.py

 DT-14-coin-change-problem

---

KMostFrequentElements.java

Array problem to find the k- most frequent elements

DT-30-Top-K-Frequent-Elements

---

DiceThrow.java
kasanishailaja/DiceThrow.java

dice throw problem to find number of ways to get sum of values on each face when all the dice are thrown.

DT-32-Dice-Throw-Problem

---

MiddleofLinkedList.java
kasanishailaja/MiddleofLinkedList.java

Linked list Problem to find the middle of a linked list.

Middle of Linked List
